### ISSUE TITLE
APIトークンを利用時のヘッダー指定について

### ISSUE THREAD

**Issue by paper29squad** [zenk-github/pytone#1]
```
from pytone import kintone

kintone = kintone.Kintone('APIトークン', 'サブドメイン', 'アプリID')
```

を実行すると
「'message': 'ユーザーのパスワード認証に失敗しました。「X-Cybozu-Authorization」ヘッダーの値が正しくありません。'}」
というエラーが返ってきます。

**X-Cybozu-Authorization**をヘッダーで送っているようですが、
APIトークンで認証するときは
**X-Cybozu-API-Token**
のヘッダーを使うようです。
手元のコードを修正したらエラーはでなくなりました。

kintone REST APIの共通仕様 – cybozu developer network
https://developer.cybozu.io/hc/ja/articles/201941754-kintone-REST-API%E3%81%AE%E5%85%B1%E9%80%9A%E4%BB%95%E6%A7%98

**Comment by MasashiTsuruya** [comment]
現在X-Cybozu-Authorizationでの認証に変更済です
